// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 31.1
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `action_payload.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:AgentAccessItem)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct AgentAccessItem {
    // message fields
    // @@protoc_insertion_point(field:AgentAccessItem.reason)
    pub reason: ::std::string::String,
    // @@protoc_insertion_point(field:AgentAccessItem.vault_name)
    pub vault_name: ::std::string::String,
    // @@protoc_insertion_point(field:AgentAccessItem.item_name)
    pub item_name: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:AgentAccessItem.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a AgentAccessItem {
    fn default() -> &'a AgentAccessItem {
        <AgentAccessItem as ::protobuf::Message>::default_instance()
    }
}

impl AgentAccessItem {
    pub fn new() -> AgentAccessItem {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "reason",
            |m: &AgentAccessItem| { &m.reason },
            |m: &mut AgentAccessItem| { &mut m.reason },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "vault_name",
            |m: &AgentAccessItem| { &m.vault_name },
            |m: &mut AgentAccessItem| { &mut m.vault_name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "item_name",
            |m: &AgentAccessItem| { &m.item_name },
            |m: &mut AgentAccessItem| { &mut m.item_name },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<AgentAccessItem>(
            "AgentAccessItem",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for AgentAccessItem {
    const NAME: &'static str = "AgentAccessItem";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.reason = is.read_string()?;
                },
                18 => {
                    self.vault_name = is.read_string()?;
                },
                26 => {
                    self.item_name = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.reason.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.reason);
        }
        if !self.vault_name.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.vault_name);
        }
        if !self.item_name.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.item_name);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.reason.is_empty() {
            os.write_string(1, &self.reason)?;
        }
        if !self.vault_name.is_empty() {
            os.write_string(2, &self.vault_name)?;
        }
        if !self.item_name.is_empty() {
            os.write_string(3, &self.item_name)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> AgentAccessItem {
        AgentAccessItem::new()
    }

    fn clear(&mut self) {
        self.reason.clear();
        self.vault_name.clear();
        self.item_name.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static AgentAccessItem {
        static instance: AgentAccessItem = AgentAccessItem {
            reason: ::std::string::String::new(),
            vault_name: ::std::string::String::new(),
            item_name: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for AgentAccessItem {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("AgentAccessItem").unwrap()).clone()
    }
}

impl ::std::fmt::Display for AgentAccessItem {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AgentAccessItem {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:ActionPayload)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ActionPayload {
    // message oneof groups
    pub content: ::std::option::Option<action_payload::Content>,
    // special fields
    // @@protoc_insertion_point(special_field:ActionPayload.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ActionPayload {
    fn default() -> &'a ActionPayload {
        <ActionPayload as ::protobuf::Message>::default_instance()
    }
}

impl ActionPayload {
    pub fn new() -> ActionPayload {
        ::std::default::Default::default()
    }

    // .AgentAccessItem agent_access_item = 1;

    pub fn agent_access_item(&self) -> &AgentAccessItem {
        match self.content {
            ::std::option::Option::Some(action_payload::Content::AgentAccessItem(ref v)) => v,
            _ => <AgentAccessItem as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_agent_access_item(&mut self) {
        self.content = ::std::option::Option::None;
    }

    pub fn has_agent_access_item(&self) -> bool {
        match self.content {
            ::std::option::Option::Some(action_payload::Content::AgentAccessItem(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_agent_access_item(&mut self, v: AgentAccessItem) {
        self.content = ::std::option::Option::Some(action_payload::Content::AgentAccessItem(v))
    }

    // Mutable pointer to the field.
    pub fn mut_agent_access_item(&mut self) -> &mut AgentAccessItem {
        if let ::std::option::Option::Some(action_payload::Content::AgentAccessItem(_)) = self.content {
        } else {
            self.content = ::std::option::Option::Some(action_payload::Content::AgentAccessItem(AgentAccessItem::new()));
        }
        match self.content {
            ::std::option::Option::Some(action_payload::Content::AgentAccessItem(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_agent_access_item(&mut self) -> AgentAccessItem {
        if self.has_agent_access_item() {
            match self.content.take() {
                ::std::option::Option::Some(action_payload::Content::AgentAccessItem(v)) => v,
                _ => panic!(),
            }
        } else {
            AgentAccessItem::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, AgentAccessItem>(
            "agent_access_item",
            ActionPayload::has_agent_access_item,
            ActionPayload::agent_access_item,
            ActionPayload::mut_agent_access_item,
            ActionPayload::set_agent_access_item,
        ));
        oneofs.push(action_payload::Content::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ActionPayload>(
            "ActionPayload",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ActionPayload {
    const NAME: &'static str = "ActionPayload";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.content = ::std::option::Option::Some(action_payload::Content::AgentAccessItem(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.content {
            match v {
                &action_payload::Content::AgentAccessItem(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let ::std::option::Option::Some(ref v) = self.content {
            match v {
                &action_payload::Content::AgentAccessItem(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ActionPayload {
        ActionPayload::new()
    }

    fn clear(&mut self) {
        self.content = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ActionPayload {
        static instance: ActionPayload = ActionPayload {
            content: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ActionPayload {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ActionPayload").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ActionPayload {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ActionPayload {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `ActionPayload`
pub mod action_payload {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:ActionPayload.content)
    pub enum Content {
        // @@protoc_insertion_point(oneof_field:ActionPayload.agent_access_item)
        AgentAccessItem(super::AgentAccessItem),
    }

    impl ::protobuf::Oneof for Content {
    }

    impl ::protobuf::OneofFull for Content {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::ActionPayload as ::protobuf::MessageFull>::descriptor().oneof_by_name("content").unwrap()).clone()
        }
    }

    impl Content {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Content>("content")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x14action_payload.proto\"e\n\x0fAgentAccessItem\x12\x16\n\x06reason\
    \x18\x01\x20\x01(\tR\x06reason\x12\x1d\n\nvault_name\x18\x02\x20\x01(\tR\
    \tvaultName\x12\x1b\n\titem_name\x18\x03\x20\x01(\tR\x08itemName\"Z\n\rA\
    ctionPayload\x12>\n\x11agent_access_item\x18\x01\x20\x01(\x0b2\x10.Agent\
    AccessItemH\0R\x0fagentAccessItemB\t\n\x07contentb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(AgentAccessItem::generated_message_descriptor_data());
            messages.push(ActionPayload::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
